COMMENT =		SSE plugin for Starlette

MODPY_DISTV =		3.4.11

DISTNAME =		sse_starlette-${MODPY_DISTV}
PKGNAME =		py-sse-starlette-${MODPY_DISTV}
REVISION =		0

CATEGORIES =		www

# BSD
PERMIT_PACKAGE =	Yes

MODULES =		lang/python

MODPY_PI =		Yes
MODPY_PYBUILD =		setuptools

RUN_DEPENDS =		net/py-anyio \
			www/py-starlette

.include <bsd.port.mk>
