COMMENT=	bidirectional mapping library

MODPY_DISTV=	0.23.1
DISTNAME=	bidict-${MODPY_DISTV}
PKGNAME=	py-bidict-${MODPY_DISTV}

CATEGORIES=	devel
HOMEPAGE=	https://bidict.readthedocs.io/

# MPL-2.0
PERMIT_PACKAGE=	Yes

MODULES=	lang/python
MODPY_PYBUILD=	setuptools
MODPY_PI=	Yes
NO_TEST=	Yes

.include <bsd.port.mk>
