#ifndef HSNETWORKCONFIG_H
#define HSNETWORKCONFIG_H
#define HAVE_NETINET_IN_H 1
#define HAVE_NETINET_TCP_H 1
#define HAVE_SYS_SOCKET_H 1
#define HAVE_SYS_UIO_H 1
#define HAVE_SYS_UN_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_FCNTL_H 1
#define HAVE_NETDB_H 1
#define HAVE_ARPA_INET_H 1
#define HAVE_NET_IF_H 1
#define HAVE_LIMITS_H 1
#define HAVE_STDLIB_H 1
#define HAVE_UNISTD_H 1
#define HAVE_GETPEEREID 1
#define HAVE_GAI_STRERROR 1
#define HAVE_ACCEPT4 1
#define HAVE_STRUCT_SOCKADDR_SA_LEN 1
#define HAVE_STRUCT_MSGHDR_MSG_CONTROL 1
#define HAVE_DECL_AI_ADDRCONFIG 1
#define HAVE_DECL_AI_ALL 0
#define HAVE_DECL_AI_NUMERICSERV 1
#define HAVE_DECL_AI_V4MAPPED 0
#define HAVE_DECL_IPV6_V6ONLY 1
#define HAVE_DECL_IPPROTO_IP 1
#define HAVE_DECL_IPPROTO_TCP 1
#define HAVE_DECL_IPPROTO_IPV6 1
#define HAVE_DECL_SO_PEERCRED 1
#define HAVE_DECL_IP_DONTFRAG 0
#define HAVE_DECL_IP_MTU_DISCOVER 0
#endif
