#!/bin/sh
#
# $OpenBSD$
#
# PROVIDE: smp_server
# REQUIRE: DAEMON
# KEYWORD: shutdown

daemon="/usr/local/bin/smp-server"
daemon_logger="daemon.info"

. /etc/rc.d/rc.subr

pexp="smp-server:.*"

rc_cmd $1
