MODGO_MODULES =	\
	github.com/clipperhouse/displaywidth	v0.6.0 \
	github.com/clipperhouse/stringish	v0.1.1 \
	github.com/clipperhouse/uax29/v2	v2.3.0 \
	github.com/cpuguy83/go-md2man/v2	v2.0.6 \
	github.com/davecgh/go-spew	v1.1.1 \
	github.com/fatih/color	v1.18.0 \
	github.com/go-ini/ini	v1.67.0 \
	github.com/inconshreveable/mousetrap	v1.1.0 \
	github.com/mattn/go-colorable	v0.1.14 \
	github.com/mattn/go-isatty	v0.0.20 \
	github.com/mattn/go-runewidth	v0.0.19 \
	github.com/olekukonko/cat	v0.0.0-20250911104152-50322a0618f6 \
	github.com/olekukonko/errors	v1.1.0 \
	github.com/olekukonko/ll	v0.1.3 \
	github.com/olekukonko/tablewriter	v1.1.2 \
	github.com/olekukonko/ts	v0.0.0-20171002115256-78ecb04241c0 \
	github.com/pmezard/go-difflib	v1.0.0 \
	github.com/russross/blackfriday/v2	v2.1.0 \
	github.com/spf13/cobra	v1.10.2 \
	github.com/spf13/pflag	v1.0.9 \
	github.com/stretchr/objx	v0.5.2 \
	github.com/stretchr/testify	v1.11.1 \
	go.yaml.in/yaml/v3	v3.0.4 \
	golang.org/x/sys	v0.37.0 \
	gopkg.in/check.v1	v0.0.0-20161208181325-20d25e280405 \
	gopkg.in/yaml.v3	v3.0.1

MODGO_MODFILES =	\
	github.com/clipperhouse/uax29/v2	v2.2.0 \
	github.com/fatih/color	v1.15.0 \
	github.com/mattn/go-colorable	v0.1.13 \
	github.com/mattn/go-isatty	v0.0.19 \
	github.com/olekukonko/cat	v0.0.0-20250908003013-b0de306c343b \
	golang.org/x/sys	v0.12.0 \
	golang.org/x/sys	v0.25.0 \
	golang.org/x/sys	v0.29.0 \
	golang.org/x/sys	v0.6.0
