MODGO_MODULES =	\
	github.com/creack/pty		 v1.1.24 \
	github.com/go-quicktest/qt	 v1.102.0 \
	github.com/google/go-cmp	 v0.7.0 \
	github.com/google/renameio/v2	 v2.0.2 \
	github.com/kr/pretty		 v0.3.1 \
	github.com/kr/text		 v0.2.0 \
	github.com/pkg/diff		 v0.0.0-20210226163009-20ebb0f2a09e \
	github.com/rogpeppe/go-internal	 v1.15.0 \
	github.com/yuin/goldmark	 v1.4.13 \
	golang.org/x/mod		 v0.29.0 \
	golang.org/x/net		 v0.46.0 \
	golang.org/x/sync		 v0.17.0 \
	golang.org/x/sys		 v0.47.0 \
	golang.org/x/telemetry		 v0.0.0-20251008203120-078029d740a8 \
	golang.org/x/term		 v0.45.0 \
	golang.org/x/tools		 v0.38.0 \
	mvdan.cc/editorconfig		 v0.3.0

MODGO_MODFILES =	\
	github.com/creack/pty		 v1.1.9 \
	github.com/google/go-cmp	 v0.6.0 \
	github.com/rogpeppe/go-internal	 v1.12.0 \
	github.com/rogpeppe/go-internal	 v1.9.0 \
	golang.org/x/mod		 v0.21.0 \
	golang.org/x/sys		 v0.26.0 \
	golang.org/x/sys		 v0.37.0 \
	golang.org/x/tools		 v0.26.0 \
	golang.org/x/tools		 v0.37.0

