COMMENT =		model context protocol types

MODPY_DISTV =		2.2.0
DISTNAME =		mcp_types-${MODPY_DISTV}
PKGNAME =		py-mcp-types-${MODPY_DISTV}

CATEGORIES =		devel

HOMEPAGE =		https://modelcontextprotocol.io/

# MIT
PERMIT_PACKAGE =	Yes

MODULES =		lang/python

MODPY_PI =		Yes
MODPY_PYBUILD =		hatchling

BUILD_DEPENDS =		devel/py-uv-dynamic-versioning

RUN_DEPENDS =		devel/py-pydantic \
			devel/py-typing-extensions

.include <bsd.port.mk>
