COMMENT =		OpenTelemetry API for Python

MODPY_DISTV =		1.44.0
DISTNAME =		opentelemetry_api-${MODPY_DISTV}
PKGNAME =		py-opentelemetry-api-${MODPY_DISTV}

CATEGORIES =		devel

HOMEPAGE =		https://opentelemetry.io/

# Apache-2.0
PERMIT_PACKAGE =	Yes

MODULES =		lang/python

MODPY_PI =		Yes
MODPY_PYBUILD =		hatchling

RUN_DEPENDS =		devel/py-typing-extensions

.include <bsd.port.mk>
