MODGO_MODULES =	\
	github.com/aymanbagabas/go-udiff	 v0.2.0 \
	github.com/charmbracelet/colorprofile	 v0.1.11 \
	github.com/charmbracelet/lipgloss/v2	 v2.0.0-alpha.2.0.20250127175135-cf3915a699b4 \
	github.com/charmbracelet/x/ansi		 v0.8.0 \
	github.com/charmbracelet/x/conpty	 v0.1.0 \
	github.com/charmbracelet/x/errors	 v0.0.0-20240508181413-e8d8b6e2de86 \
	github.com/charmbracelet/x/exp/golden	 v0.0.0-20241029204245-3ef5e7b1ea37 \
	github.com/charmbracelet/x/term		 v0.2.1 \
	github.com/charmbracelet/x/termios	 v0.1.0 \
	github.com/charmbracelet/x/xpty		 v0.1.1 \
	github.com/cpuguy83/go-md2man/v2	 v2.0.4 \
	github.com/creack/pty			 v1.1.24 \
	github.com/davecgh/go-spew		 v1.1.1 \
	github.com/inconshreveable/mousetrap	 v1.1.0 \
	github.com/lucasb-eyer/go-colorful	 v1.2.0 \
	github.com/mattn/go-runewidth		 v0.0.16 \
	github.com/muesli/cancelreader		 v0.2.2 \
	github.com/pmezard/go-difflib		 v1.0.0 \
	github.com/rivo/uniseg			 v0.4.7 \
	github.com/russross/blackfriday/v2	 v2.1.0 \
	github.com/spf13/cobra			 v1.8.1 \
	github.com/spf13/pflag			 v1.0.5 \
	github.com/stretchr/objx		 v0.5.2 \
	github.com/stretchr/testify		 v1.10.0 \
	github.com/xo/terminfo			 v0.0.0-20220910002029-abceb7e1c41e \
	golang.org/x/exp			 v0.0.0-20231006140011-7918f672742d \
	golang.org/x/sys			 v0.29.0 \
	gopkg.in/check.v1			 v0.0.0-20161208181325-20d25e280405 \
	gopkg.in/yaml.v3			 v3.0.1

MODGO_MODFILES =	\
	github.com/charmbracelet/colorprofile	 v0.1.10 \
	github.com/charmbracelet/x/exp/golden	 v0.0.0-20240806155701-69247e0abc2a \
	github.com/rivo/uniseg			 v0.2.0 \
	golang.org/x/exp			 v0.0.0-20220909182711-5c715a9e8561 \
	golang.org/x/sys			 v0.0.0-20220204135822-1c1b9b1eba6a \
	golang.org/x/sys			 v0.20.0 \
	golang.org/x/sys			 v0.26.0 \
	golang.org/x/sys			 v0.27.0

