COMMENT =		personal markdown scribe with template support

MODGO_MODNAME =		github.com/charmbracelet/markscribe
MODGO_VERSION =		v0.8.1

DISTNAME =		markscribe-${MODGO_VERSION}

CATEGORIES =		textproc

HOMEPAGE =		https://github.com/charmbracelet/markscribe

MAINTAINER =		David Uhden Collado <daviduhden@gmail.com>

# MIT
PERMIT_PACKAGE =	Yes

WANTLIB +=		c pthread

MODULES =		lang/go

.include "modules.inc"

.include <bsd.port.mk>
