COMMENT =		back up and restore SSH keys with seed words

MODGO_MODNAME =		github.com/charmbracelet/melt
MODGO_VERSION =		v0.6.2

DISTNAME =		melt-${MODGO_VERSION}

CATEGORIES =		security

HOMEPAGE =		https://github.com/charmbracelet/melt

MAINTAINER =		David Uhden Collado <daviduhden@gmail.com>

# MIT
PERMIT_PACKAGE =	Yes

WANTLIB +=		c pthread

MODULES =		lang/go

.include "modules.inc"

.include <bsd.port.mk>
