COMMENT =		SSH server with terminal visual effects

MODGO_MODNAME =		github.com/charmbracelet/confettysh
MODGO_VERSION =		v1.1.2

DISTNAME =		confettysh-${MODGO_VERSION}

CATEGORIES =		misc

HOMEPAGE =		https://github.com/charmbracelet/confettysh

MAINTAINER =		David Uhden Collado <daviduhden@gmail.com>

# MIT
PERMIT_PACKAGE =	Yes

WANTLIB +=		c pthread

MODULES =		lang/go

.include "modules.inc"

.include <bsd.port.mk>
