COMMENT =		personal key value store

MODGO_MODNAME =		github.com/charmbracelet/skate
MODGO_VERSION =		v1.1.0

DISTNAME =		skate-${MODGO_VERSION}

CATEGORIES =		databases

HOMEPAGE =		https://github.com/charmbracelet/skate

MAINTAINER =		David Uhden Collado <daviduhden@gmail.com>

# MIT
PERMIT_PACKAGE =	Yes

WANTLIB +=		c pthread

MODULES =		lang/go

.include "modules.inc"

.include <bsd.port.mk>
