Index: src-qt5/core/lumina-desktop/defaults/luminaDesktop.conf
--- a/src-qt5/core/lumina-desktop/defaults/luminaDesktop.conf
+++ b/src-qt5/core/lumina-desktop/defaults/luminaDesktop.conf
@@ -62,7 +62,7 @@ theme_fontsize=10pt #Default size of the fonts to use on the desktop (can also u
 
 #DESKTOP SETTINGS (used for the primary screen in multi-screen setups)
 desktop_visiblepanels=2 #[0 - 12] The number of panels visible by default
-desktop_backgroundfiles=/usr/share/wallpapers/default
+desktop_backgroundfiles=/usr/local/share/wallpapers/default
 desktop_backgroundrotateminutes=5 #[positive integer] number of minutes between background rotations (if multiple files)
 #desktop_plugins= #list of plugins to be shown on the desktop by default
 desktop_generate_icons=true #[true/false] Auto-generate launchers for ~/Desktop items
@@ -83,7 +83,7 @@ panel2_pinlocation=center
 panel2_edgepercent=24
 
 #MENU SETTINGS (right-click menu)
-menu_plugins=terminal, filemanager, applications, line, jsonmenu::::/usr/share/lumina-desktop/menu-scripts/ls.json.sh::::Home::::user-home, jsonmenu::::/usr/share/lumina-desktop/menu-scripts/ls.json.sh /::::Root::::folder-orange, line, settings, line, lockdesktop
+menu_plugins=terminal, filemanager, applications, line, jsonmenu::::/usr/local/share/lumina-desktop/menu-scripts/ls.json.sh::::Home::::user-home, jsonmenu::::/usr/local/share/lumina-desktop/menu-scripts/ls.json.sh /::::Root::::folder-orange, line, settings, line, lockdesktop
 
 #FAVORITES CUSTOMIZATION
 #favorites_add=<file/dir path> #Create a favorites entry for this file/dir
